<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>

<div class="box-price price-container row">
<?php
if (is_numeric($_product->getMsrp())) {
    $minAdvertisedPrice = 'A$' . number_format($_product->getMsrp(), 2);
}  else {
    $minAdvertisedPrice = 'A$0.00' ;
}
if (is_numeric($_product->getPrice())) {
    $pckPrice = 'A$' . number_format($_product->getPrice(), 2);
} else {
    $pckPrice = 'A$0.00' ;
}
if ($minAdvertisedPrice > 0) {
    echo '<div class="col-md-3 price-msrp_price old-price price-wrapper">' . $minAdvertisedPrice . ' <small>RRP</small></div>';
    echo '<div class="col-md-3 actual-price">' . $pckPrice . ' <small>PCK Price</small></div>';
}
?>
</div>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
